FROM python:3.7

RUN apt-get update \
  && apt-get install -y apt-utils \
  && apt-get install -y build-essential \
  && apt-get autoremove && apt-get autoclean

ENV PYTHONUNBUFFERED 1

RUN mkdir /code

WORKDIR /code

COPY requirements.txt /code/

RUN pip install -U pip && pip install wheel
RUN pip install -r requirements.txt
